server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://transaction-mongo:27017/transaction-db

app:
  bowlingball-service:
    host: bowlingball-service
    port: 8080

  shoe-service:
    host: shoe-service
    port: 8080

  lane-service:
    host: lane-service
    port: 8080
